package com.varun.taskmgmtapi.dto.TaskDto;


import jakarta.validation.constraints.NotBlank;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDate;

@Getter
@Setter //we need setters here, because FE is sending JSON, and jackson will use this JSON and convert it to java obj
//of datatype CreateTaskRequest, so we need to set the values of attributes/fields of CreateTaskRequest class/obj with
//the help of JSON
public class CreateTaskRequest {

    @NotBlank(message = "taskname is required")
    private String taskName;
    private String taskDescription;
    private LocalDate dueDate;

}
/*
no need to send id(automatically generated by DB). Also updatedAt, createdAt will be taken care by 'entity' itslf
and no status as 'entity' itself has private TaskStatus status=TaskStatus.TODO
so a new task created starts as TODO



 */
